<template>
  <scroll>
      <ul>
        <li>分数1</li>
        <li>分数2</li>
        <li>分数3</li>
        <li>分数4</li>
        <li>分数5</li>
        <li>分数6</li>
        <li>分数7</li>
        <li>分数8</li>
        <li>分数9</li>
        <li>分数10</li>
        <li>分数11</li>
        <li>分数12</li>
        <li>分数13</li>
        <li>分数14</li>
        <li>分数15</li>
        <li>分数16</li>
        <li>分数17</li>
        <li>分数18</li>
        <li>分数19</li>
        <li>分数20</li>
        <li>分数21</li>
        <li>分数22</li>
        <li>分数23</li>
        <li>分数24</li>
        <li>分数25</li>
        <li>分数26</li>
        <li>分数27</li>
        <li>分数28</li>
        <li>分数29</li>
        <li>分数30</li>
        <li>分数31</li>
        <li>分数32</li>
        <li>分数33</li>
        <li>分数34</li>
        <li>分数35</li>
        <li>分数36</li>
        <li>分数37</li>
        <li>分数38</li>
        <li>分数39</li>
        <li>分数40</li>
        <li>分数41</li>
        <li>分数42</li>
        <li>分数43</li>
        <li>分数44</li>
        <li>分数45</li>
        <li>分数46</li>
        <li>分数47</li>
        <li>分数48</li>
        <li>分数49</li>
        <li>分数50</li>
        <li>分数51</li>
        <li>分数52</li>
        <li>分数53</li>
        <li>分数54</li>
        <li>分数55</li>
        <li>分数56</li>
        <li>分数57</li>
        <li>分数58</li>
        <li>分数59</li>
        <li>分数60</li>
        <li>分数61</li>
        <li>分数62</li>
        <li>分数63</li>
        <li>分数64</li>
        <li>分数65</li>
        <li>分数66</li>
        <li>分数67</li>
        <li>分数68</li>
        <li>分数69</li>
        <li>分数70</li>
        <li>分数71</li>
        <li>分数72</li>
        <li>分数73</li>
        <li>分数74</li>
        <li>分数75</li>
        <li>分数76</li>
        <li>分数77</li>
        <li>分数78</li>
        <li>分数79</li>
        <li>分数80</li>
        <li>分数81</li>
        <li>分数82</li>
        <li>分数83</li>
        <li>分数84</li>
        <li>分数85</li>
        <li>分数86</li>
        <li>分数87</li>
        <li>分数88</li>
        <li>分数89</li>
        <li>分数90</li>
        <li>分数91</li>
        <li>分数92</li>
        <li>分数93</li>
        <li>分数94</li>
        <li>分数95</li>
        <li>分数96</li>
        <li>分数97</li>
        <li>分数98</li>
        <li>分数99</li>
        <li>分数100</li>
      </ul>
  </scroll>
</template>

<script>
import scroll from "components/common/componets/Scroll"

  export default {
    name: "Category",
    components:{
      scroll
    }
  }
</script>

<style scoped>
  .wrapper{
    height: 150px;
    background: violet;
    overflow: hidden;
  }
</style>
